---
title: "Data loader"
---

The data loading step ensures all possbile ways of passing raw data are coerced into in-memory SpikeInterface objects.

It should exist as a convenience function rather than as a fixed step in the pipeline, as its output may be passed to any of [raw data metrics](pipeline-steps.qmd#raw-data-quality-metrics), [artefact detection](pipeline-steps.qmd#artifact-detection), [artefact curation](pipeline-steps.qmd#artifact-curation), [preprocessing](pipeline-steps.qmd#preprocessing), or the [full pipeline](index.qmd#pipeline-steps). As such, no information related to data loading (e.g. file paths) is encoded in the [`CONFIG`](outputs.qmd#config).


It essentially takes SpikeInterface recordings, or paths to raw data, and ensures they are loaded SpikeInterface recordings with probes attached. If recordings are concatenated, this is detected and concatenation times flagged.

**INPUTS:**

- A [`RAW_DATA_PATH`](outputs.qmd#raw-data-path), [`RAW_DATA_PATH_SESSION_LIST`](outputs.qmd#raw-data-path-session-list), [`SPIKEINTERFACE_REC`](outputs.qmd#spikeinterface-rec), or [`SPIKEINTERFACE_REC_SESSION_LIST`](outputs.qmd#spikeinterface-rec-session-list).
- (optional) a `bool` flag for producing a [`DEBUGGING_REC`](outputs.qmd#debugging-rec)
- (optional) a `STREAM_NAME` in case the AP stream cannot be automatically detected.
- (optional) a [`PROBE`](outputs.qmd#probe) to set on all loaded recordings in case it cannot be automatically loaded.
- (optional) a `split_by_shank` option.

**OUTPUTS:**

- a [`DATA_LOADER_OUTPUT_RECORDINGS`](outputs.qmd#data-loader-output-recordings).

**OPERATIONS:**

- Load a [`RAW_DATA_PATH`](outputs.qmd#raw-data-path) or [`RAW_DATA_PATH_SESSION_LIST`](outputs.qmd#raw-data-path-session-list) to [`SPIKEINTERFACE_REC`](outputs.qmd#spikeinterface-rec) or [`SPIKEINTERFACE_REC_SESSION_LIST`](outputs.qmd#spikeinterface-rec-session-list), respectively.  
- (optional) time slice the recordings to produce a [`DEBUGGING_REC`](outputs.qmd#debugging-rec).
- Automatically determine the AP stream, otherwise use `STREAM_NAME`. 
- Set a passed `PROBE` on the recordings, if passed and they are not automatically detected.

**CHECKS:**

- Error if no probe found in the loaded or passed recordings and `PROBE` is not passed.
- Error if cannot determine AP stream and no `STREAM_NAME` provided.
- Error if sessions do not have the same probe, sampling rate, data type etc. Do a confidence check on the session times if `time_vector` is set.
