title: "Inputs and Outputs"

Data objects and files passed between the stages in [Pipeline steps](pipeline-steps.qmd). Definitions to be added. On-disk locations are resolved relative to `PROJECT_PATH`.

## Inputs

### `RAW_DATA_PATH` {#raw-data-path}

A filepath to any raw data files or folders that can be loaded by SpikeInterface (e.g. SpikeGLX, Open Ephys, SpikeInterface folder).

### `RAW_DATA_PATH_SESSION_LIST` {#raw-data-path-session-list}

A Python list of `RAW_DATA_PATH`.

### `SPIKEINTERFACE_REC` {#spikeinterface-rec}

An in-memory SpikeInterface [`Recording`](https://spikeinterface.readthedocs.io/en/stable/api.html#spikeinterface.core.BaseRecording) object.

If split by shank, the `SPIKEINTERFACE_REC` may be a dictionary where the keys are shank name and values are recording for that shank e.g. `recording=[{"0": Recording1, "1": Recording2}, {"0": Recording3, "1": Recording4}]`

### `SPIKEINTERFACE_REC_SESSION_LIST` {#spikeinterface-rec-session-list}

A Python list of `SPIKEINTERFACE_REC`.


### `DEBUGGING_REC` {#debugging-rec}

A `SPIKEINTERFACE_REC` that has been cut down to allow the pipeline to run quickly.

The default time to cut a recording down to is 30 seconds, based on the Allen pipeline (as of 02/09/2026).

### `DATA_LOADER_OUTPUT_RECORDINGS` {#data-loader-output-recordings}

The data returned by the data loader. It may be a [`SPIKEINTERFACE_REC`](#spikeinterface-rec), a [`SPIKEINTERFACE_REC_SESSION_LIST`](#spikeinterface-rec-session-list), a [`DEBUGGING_REC`](#debugging-rec) or list thereof. 


### `PREPROCESSED_OUTPUT_RECORDINGS` {#preprocessed-output-recordings}

Takes the form `DATA_LOADER_OUTPUT_RECORDINGS` but the recordings are the final output of the preprocessing step.

### `CONCAT_REC_TIMES` {#concat-rec-times}

A CSV or [pandas `DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) containing the start and stop times of sessions which have been concatenated. This can be used by the pipeline to split the sorting.

Each row contains the start and stop times of one session, in seconds.

The two columns are:

- `"start_time"`: session start time, as a float
- `"stop_time"`: session stop time, as a float

### `PROBE` {#probe}

A ProbeInterface [`Probe`](https://probeinterface.readthedocs.io/en/main/api.html#probeinterface.Probe) object.

### `PROJECT_PATH` {#project-path}

The root directory for the pipeline output. Here outputs from steps are saved and used as inputs for following steps.

### `CONFIG` {#config}

The YAML configuration file for the pipeline. See [Config](config.qmd) for the full example and specification.

## Outputs

### `RAW_DATA_QUALITY_METRICS` {#raw-data-quality-metrics}

A set of metrics that estimate the quality of raw data, based on the IBL [spike-sorting white paper](https://doi.org/10.6084/m9.figshare.19705522). 

For steps that are measured after preprocessing, `phase_shift`, a TEMPORAL_FILTER and COMMON_REFERENCE step are applied, based on the CONFIG.

These metrics are computed and stored on disk, and used to generate [`RAW_DATA_QUALITY_PLOTS`](#raw-data-quality-plots). No hard thresholds are applied to these metrics to determine inclusion or exclusion of data, instead this is decided by visual inspection of the plots.

**Before and after preprocessing:**

- **RMS (AP and LFP bands):** To obtain a quick measure of data quality, RMS is computed from one 1-second chunk every 300 seconds. The following summary metrics are then calculated:

    - Median RMS per channel across the sampled chunks.
    - 10th and 90th percentiles of the per-channel median RMS values, providing a measure of RMS variability across the probe.

    A full per-channel RMS map is then computed across the entire recording using consecutive windows approximately 3 seconds long (8192 samples for a Neuropixels 1.0 probe). These maps are used to generate [`RAW_DATA_QUALITY_PLOTS`](#raw-data-quality-plots).

**After preprocessing:**

- **Spectral Density AP** AP-band power spectral density in $V^2/Hz$ computed per channel using Welch's method.
- **Spectral Density LFP** LFP-band power spectral density in $V^2/Hz$ computed per channel using Welch's method.
- **Spike Rate** spike-like events per second from simple threshold detection on the preprocessed AP signal. These spikes can be overlaid on the RMS or raw data to get a first idea if any spikes are detectable from the data and if issues in the RMS appear to translate to issues in spike detection.

**TODO: specify format for storage**
**TODO: determine chunking rules**

### `RAW_DATA_QUALITY_PLOTS` {#raw-data-quality-plots}

Plots used for quality-assessment, saved as `.png`. These are computed from the `RAW_DATA_QUALITY_METRICS` as developed by the [IBL](https://doi.org/10.6084/m9.figshare.19705522).

- **AP-band and LFP-band RMS**: a time x channel plot of RMS. Separate plots contrasting before and after preprocessing.
- **Spikes on RMS**: time x channel preprocessed RMS plot with detected spike time overlaid.
- **AP-band and LFP-band Spectral Density**: a channel x frequency heatmap with intensity representing power, $V^2/Hz$

### `BAD_CHANNEL_DETECTION_METRICS` {#detect-bad-channels-metrics}

The scores for each channel on the IBL's three metrics used for bad channel detection. Also RMS for each channel.

### `BAD_CHANNEL_DETECTION_PLOTS` {#detect-bad-channels-plots}

Plots of `BAD_CHANNEL_DETECTION_METRICS` as shown in figure 4 of the [IBL white paper.](https://figshare.com/articles/online_resource/Spike_sorting_pipeline_for_the_International_Brain_Laboratory/19705522?file=49783080).

### `CONCAT_POINTS_QUALITY_METRICS` {#concat-points-quality-metrics}

This is hypothetical set of quality metrics that check RMS and other QA across the concatenation points of recordings,

### `CONCAT_POINTS_QUALITY_METRICS_PLOTS` {#concat-points-quality-metrics-plots}

Plots of preprocessed data at the concatenation point of recordings. Possibly plots of `CONCAT_POINTS_QUALITY_METRICS`.

### `ARTEFACT_DETECTION_PLOTS` {#artefact-detection-plots}

A plot of a random selection of detected artefact periods denoted by a linear region overlaid on the preprocessed data.

### `PREPROCESS_STEP_PLOTS` {#preprocess-step-plots}

A plot of the data at each preprocessing stage.

### `MOTION_CORRECTION_PLOTS` {#motion-correction-plots}

See [plot_motion()](https://spikeinterface.readthedocs.io/en/latest/api.html#spikeinterface.widgets.plot_motion).

### `SESSION_CONCATENATION_PLOTS` {#session-concatenation-plots}

Plots that show the preprocessed data across the concatenation points for each session. 
**TODO:** this could be supplemented by quality metrics across these boundaries, inter-session alignment plots.


### `BAD_CHANNEL_IDS` {#bad-channel-ids}

The channel IDs identified as bad by the detect-bad-channels step.

### `BAD_CHANNEL_LABELS` {#bad-channel-labels}

The bad-channel classification associated with each `BAD_CHANNEL_ID`.

### `EVENT_PERIODS_CSV` {#event-periods-csv}

A CSV or [pandas `DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) containing the start and stop times of periods
detected as artefacts.

Each row is a detected period.

The three columns are:

- `"start_time"`: taking float values
- `"stop_time"`: taking float values
- (optional) `label`: Label of the event period. Permitted values are `SATURATION` or `ENVELOPE`. 

### `EVENT_PERIODS_CURATED_CSV` {#event-periods-curated-csv}

An `EVENT_PERIODS_CSV` is a CSV file that has been curated. It is the same format of
`EVENT_PERIODS_CSV`. It indicates it has been manually curated by including the suffix `_curated`
in the filename.

### `SORTING` {#sorting}

A SpikeInterface [`BaseSorting`](https://spikeinterface.readthedocs.io/en/stable/api.html#spikeinterface.core.BaseSorting) object.

### `SORTING_ANALYZER` {#sorting-analyzer}

A SpikeInterface [`SortingAnalyzer`](https://spikeinterface.readthedocs.io/en/stable/api.html#spikeinterface.core.SortingAnalyzer) object.

### `SORTER_REPORT` {#sorter-report}

The report produced for the SpikeInterface sorting result.

### `QUALITY_METRICS_CSV` {#quality-metrics-csv}

Per-unit quality metrics table, following SpikeInterface quality metrics in [`quality_metrics.metric_names`](https://github.com/AllenNeuralDynamics/aind-ephys-pipeline/blob/main/docs/source/parameters.rst):

**TODO:** log and/or link to the exact quality metrics used and their definitions

### `POSTPROCESSING_PLOTS` {#postprocessing-plots}

The collection of plots generated during postprocessing.

**TODO: fill in** (for the most part these will )

#### `TEMPLATE_PLOTS` {#template-plots}

#### `WAVEFORM_PLOTS` {#waveform-plots}

#### `CLUSTER_PLOTS` {#cluster-plots}

#### `UNIT_LOCATION_PLOTS` {#unit-location-plots}

#### `AUTOCORRELOGRAM_PLOTS` {#autocorrelogram-plots}

#### `CROSSCORRELOGRAM_PLOTS` {#crosscorrelogram-plots}

#### `FIRING_RATE_PLOTS` {#firing-rate-plots}

#### `QUALITY_METRIC_PLOTS` {#quality-metric-plots}

